### ISSUE TITLE
Output to CSV

### ISSUE THREAD

**Issue by Winter** [Dijji/XstReader#5]
Rather than attempting to create an entire PST file, which as mentioned in #1 is a lot of work; Just output to a CSV. Most* email clients are able to take advantage of CSV importing / exporting. The problem is we just can't open a lot of our OST/PST files which _XstReader_ is able to pull data from.

**Comment by pemguin005** [comment]
Dijji, thanks for the redirect to this issue. And yes, what you've described sounds perfect.

For my needs, a multi-row CSV with the contact properties would be perfect. Rebuilding lost contact lists from corrupt OST files has caused me issues on more than one occasion where users prefer a local address book. Using XstReader to open and old OST and pipe contact properties out to a CSV would solve my problem entirely I think. Microsoft has a CSV Contact template for easy contact importing, so if i could pull a CSV with XstReader, and pass that info into their template, I'd have the perfect recipe to solve the issue entirely.

**Comment by pemguin005** [comment]
Just tried out v1.4. That export option is awesome! I bet it'll work perfectly. My tests of the feature make it seem perfect. 

I'm reaching out to some folks who lost their contact lists recently and I'm going to try using the exporter on their old OST to rebuild their contacts list and put it into an Outlook importable .csv file. I'm very excited about this.

Very fine work Dijji!

**Comment by sutekh849** [comment]
Would it be possible to add an option to export messages to CSV too? The present function works fine for contacts, but if you've got mail that failed to sync to the remote imap server in an ost file you need to recover (Don't ask) and try to export that, the output isn't readable by outlook's import CSV wizard.

**Comment by Dijji** [comment]
Actually, the current CSV output is not readable by Outlook for Contacts, either. You have to edit the columns and titles down to the specific ones that Outlook expects.

The same holds true for messages, except that the message body is not included in the CSV. However, if only a few messages are involved, you can use the CSV to retrieve blank messages into Outlook, then copy and paste the body from the mail body window in the viewer.

I have deliberately stopped short of providing a mass email export option, partly because there is no universal standard format to export to, and partly out of respect for the developers earning a living by writing and selling software that does the job (although I agree, their marketing practices are often highly dubious: there appears to have been an unfortunate competitive race to the bottom in this regard).

Dijji
